///////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2002-2020, Open Design Alliance (the "Alliance").
// All rights reserved.
//
// This software and its documentation and related materials are owned by
// the Alliance. The software may only be incorporated into application
// programs owned by members of the Alliance, subject to a signed
// Membership Agreement and Supplemental Software License Agreement with the
// Alliance. The structure and organization of this software are the valuable
// trade secrets of the Alliance and its suppliers. The software is also
// protected by copyright law and international treaty provisions. Application
// programs incorporating this software must include the following statement
// with their copyright notices:
//
//   This application incorporates Open Design Alliance software pursuant to a license
//   agreement with Open Design Alliance.
//   Open Design Alliance Copyright (C) 2002-2020 by Open Design Alliance.
//   All rights reserved.
//
// By use of this software, its documentation or related materials, you
// acknowledge and accept the above terms.
///////////////////////////////////////////////////////////////////////////////

#ifndef __BM_BUILD_SETTINGS_H__
#define __BM_BUILD_SETTINGS_H__

#include "OdPlatformSettings.h"

#ifdef ODA_BM_BASE_EXPORTS
  #define TB_BASE_EXPORT            OD_TOOLKIT_EXPORT
  #define TB_BASE_EXPORT_STATIC     OD_STATIC_EXPORT
#else
  #define TB_BASE_EXPORT            OD_TOOLKIT_IMPORT
  #define TB_BASE_EXPORT_STATIC     OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_COMMON_EXPORTS
  #define TB_COMMON_EXPORT            OD_TOOLKIT_EXPORT
  #define TB_COMMON_EXPORT_STATIC     OD_STATIC_EXPORT
#else
  #define TB_COMMON_EXPORT            OD_TOOLKIT_IMPORT
  #define TB_COMMON_EXPORT_STATIC     OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_EXPORTS
  #define TB_EXPORT            OD_TOOLKIT_EXPORT
  #define TB_EXPORT_STATIC     OD_STATIC_EXPORT
#else
  #define TB_EXPORT            OD_TOOLKIT_IMPORT
  #define TB_EXPORT_STATIC     OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_MODELERGEOMETRY_EXPORTS
  #define TB_MODELERGEOMETRY_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_MODELERGEOMETRY_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_MODELERGEOMETRY_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_MODELERGEOMETRY_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_LOADER_BASE_EXPORTS
  #define TB_LOADER_BASE_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_LOADER_BASE_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_LOADER_BASE_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_LOADER_BASE_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_LOADER_EXPORTS
  #define TB_LOADER_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_LOADER_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_LOADER_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_LOADER_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_BREPBUILDER_EXPORTS
  #define TB_BREPBUILDER_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_BREPBUILDER_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_BREPBUILDER_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_BREPBUILDER_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_COLLADAIMPORT_EXPORTS
  #define TB_COLLADAIMPORT_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_COLLADAIMPORT_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_COLLADAIMPORT_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_COLLADAIMPORT_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_EXPORTUTILS_EXPORTS
  #define TB_EXPORTUTILS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_EXPORTUTILS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_EXPORTUTILS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_EXPORTUTILS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_ANALYTICAL_EXPORTS
  #define TB_ANALYTICAL_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_ANALYTICAL_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_ANALYTICAL_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_ANALYTICAL_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_ARCHITECTURE_EXPORTS
  #define TB_ARCHITECTURE_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_ARCHITECTURE_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_ARCHITECTURE_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_ARCHITECTURE_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_DB_EXPORTS
  #define TB_DB_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_DB_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_DB_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_DB_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_ESSENTIAL_EXPORTS
  #define TB_ESSENTIAL_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_ESSENTIAL_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_ESSENTIAL_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_ESSENTIAL_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FAMILY_EXPORTS
  #define TB_FAMILY_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FAMILY_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FAMILY_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FAMILY_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2011_CLASSES_EXPORTS
  #define TB_FORMAT_2011_CLASSES_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2011_CLASSES_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2011_CLASSES_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2011_CLASSES_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2011_READERS_EXPORTS
  #define TB_FORMAT_2011_READERS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2011_READERS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2011_READERS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2011_READERS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2012_CLASSES_EXPORTS
  #define TB_FORMAT_2012_CLASSES_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2012_CLASSES_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2012_CLASSES_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2012_CLASSES_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2012_READERS_EXPORTS
  #define TB_FORMAT_2012_READERS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2012_READERS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2012_READERS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2012_READERS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2013_CLASSES_EXPORTS
  #define TB_FORMAT_2013_CLASSES_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2013_CLASSES_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2013_CLASSES_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2013_CLASSES_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2013_READERS_EXPORTS
  #define TB_FORMAT_2013_READERS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2013_READERS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2013_READERS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2013_READERS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2014_CLASSES_EXPORTS
  #define TB_FORMAT_2014_CLASSES_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2014_CLASSES_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2014_CLASSES_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2014_CLASSES_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2014_READERS_EXPORTS
  #define TB_FORMAT_2014_READERS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2014_READERS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2014_READERS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2014_READERS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2015_CLASSES_EXPORTS
  #define TB_FORMAT_2015_CLASSES_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2015_CLASSES_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2015_CLASSES_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2015_CLASSES_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2015_READERS_EXPORTS
  #define TB_FORMAT_2015_READERS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2015_READERS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2015_READERS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2015_READERS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2016_CLASSES_EXPORTS
  #define TB_FORMAT_2016_CLASSES_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2016_CLASSES_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2016_CLASSES_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2016_CLASSES_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2016_READERS_EXPORTS
  #define TB_FORMAT_2016_READERS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2016_READERS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2016_READERS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2016_READERS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2017_CLASSES_EXPORTS
  #define TB_FORMAT_2017_CLASSES_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2017_CLASSES_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2017_CLASSES_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2017_CLASSES_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2017_READERS_EXPORTS
  #define TB_FORMAT_2017_READERS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2017_READERS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2017_READERS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2017_READERS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2018_CLASSES_EXPORTS
  #define TB_FORMAT_2018_CLASSES_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2018_CLASSES_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2018_CLASSES_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2018_CLASSES_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2018_READERS_EXPORTS
  #define TB_FORMAT_2018_READERS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2018_READERS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2018_READERS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2018_READERS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2019_CLASSES_EXPORTS
  #define TB_FORMAT_2019_CLASSES_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2019_CLASSES_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2019_CLASSES_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2019_CLASSES_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2019_READERS_EXPORTS
  #define TB_FORMAT_2019_READERS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2019_READERS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2019_READERS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2019_READERS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2020_CLASSES_EXPORTS
  #define TB_FORMAT_2020_CLASSES_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2020_CLASSES_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2020_CLASSES_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2020_CLASSES_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2020_READERS_EXPORTS
  #define TB_FORMAT_2020_READERS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2020_READERS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2020_READERS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2020_READERS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2021_CLASSES_EXPORTS
  #define TB_FORMAT_2021_CLASSES_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2021_CLASSES_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2021_CLASSES_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2021_CLASSES_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2021_READERS_EXPORTS
  #define TB_FORMAT_2021_READERS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2021_READERS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2021_READERS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2021_READERS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_2021_WRITERS_EXPORTS
  #define TB_FORMAT_2021_WRITERS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_2021_WRITERS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_2021_WRITERS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_2021_WRITERS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_COMMON_CLASSES_EXPORTS
  #define TB_FORMAT_COMMON_CLASSES_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_COMMON_CLASSES_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_COMMON_CLASSES_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_COMMON_CLASSES_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_FORMAT_COMMON_READERS_EXPORTS
  #define TB_FORMAT_COMMON_READERS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_FORMAT_COMMON_READERS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_FORMAT_COMMON_READERS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_FORMAT_COMMON_READERS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_GEOMETRY_EXPORTS
  #define TB_GEOMETRY_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_GEOMETRY_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_GEOMETRY_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_GEOMETRY_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_GEOMETRYUTILS_EXPORTS
  #define TB_GEOMETRYUTILS_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_GEOMETRYUTILS_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_GEOMETRYUTILS_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_GEOMETRYUTILS_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_HOSTOBJ_EXPORTS
  #define TB_HOSTOBJ_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_HOSTOBJ_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_HOSTOBJ_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_HOSTOBJ_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_MAIN_EXPORTS
  #define TB_MAIN_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_MAIN_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_MAIN_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_MAIN_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_MEP_EXPORTS
  #define TB_MEP_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_MEP_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_MEP_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_MEP_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_REBAR_EXPORTS
  #define TB_REBAR_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_REBAR_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_REBAR_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_REBAR_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_STAIRSRAMP_EXPORTS
  #define TB_STAIRSRAMP_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_STAIRSRAMP_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_STAIRSRAMP_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_STAIRSRAMP_EXPORT_STATIC   OD_STATIC_IMPORT
#endif

#ifdef ODA_BM_STRUCTURAL_EXPORTS
  #define TB_STRUCTURAL_EXPORT          OD_TOOLKIT_EXPORT
  #define TB_STRUCTURAL_EXPORT_STATIC   OD_STATIC_EXPORT
#else
  #define TB_STRUCTURAL_EXPORT          OD_TOOLKIT_IMPORT
  #define TB_STRUCTURAL_EXPORT_STATIC   OD_STATIC_IMPORT
#endif



#define NOTHING_EXTRACT
#define EXTRACT(...) EXTRACT __VA_ARGS__
#define BM_PASTE(x, ...) x ## __VA_ARGS__
#define BM_EVALUATING_PASTE(x, ...) BM_PASTE(x, __VA_ARGS__)
#define BM_UNPAREN(x) BM_EVALUATING_PASTE(NOTHING_, EXTRACT x)


#endif // __BM_BUILD_SETTINGS_H__

