///////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2002-2020, Open Design Alliance (the "Alliance").
// All rights reserved.
//
// This software and its documentation and related materials are owned by
// the Alliance. The software may only be incorporated into application
// programs owned by members of the Alliance, subject to a signed
// Membership Agreement and Supplemental Software License Agreement with the
// Alliance. The structure and organization of this software are the valuable
// trade secrets of the Alliance and its suppliers. The software is also
// protected by copyright law and international treaty provisions. Application
// programs incorporating this software must include the following statement
// with their copyright notices:
//
//   This application incorporates Open Design Alliance software pursuant to a license
//   agreement with Open Design Alliance.
//   Open Design Alliance Copyright (C) 2002-2020 by Open Design Alliance.
//   All rights reserved.
//
// By use of this software, its documentation or related materials, you
// acknowledge and accept the above terms.
///////////////////////////////////////////////////////////////////////////////

#ifndef _BM_UNITSYMBOLTYPE_H_
#define _BM_UNITSYMBOLTYPE_H_

#define ODBM_UNITSYMBOLTYPE(PARAM_DEF, ...)                                                                                                                                                  \
  PARAM_DEF(UST_CUSTOM,                                  0xFFFFFFFF, not_std::nullopt,                               L"autodesk.unit.symbol:custom-1.0.0")                                   \
  PARAM_DEF(UST_NONE,                                    0x00000000, not_std::nullopt,                               not_std::nullopt)                                                       \
  PARAM_DEF(UST_M,                                       0x00000001, L"m",                                           L"autodesk.unit.symbol:meter-1.0.0")                                    \
  PARAM_DEF(UST_CM,                                      0x00000065, L"cm",                                          L"autodesk.unit.symbol:cm-1.0.1")                                       \
  PARAM_DEF(UST_MM,                                      0x000000C9, L"mm",                                          L"autodesk.unit.symbol:mm-1.0.1")                                       \
  PARAM_DEF(UST_LF,                                      0x0000012D, L"LF",                                          L"autodesk.unit.symbol:lf-1.0.1")                                       \
  PARAM_DEF(UST_FOOT_SINGLE_QUOTE,                       0x0000012E, L"'",                                           L"autodesk.unit.symbol:footSingleQuote-1.0.1")                          \
  PARAM_DEF(UST_FT,                                      0x0000012F, L"ft",                                          L"autodesk.unit.symbol:ft-1.0.1")                                       \
  PARAM_DEF(UST_INCH_DOUBLE_QUOTE,                       0x00000259, L"\"",                                          L"autodesk.unit.symbol:inchDoubleQuote-1.0.1")                          \
  PARAM_DEF(UST_IN,                                      0x0000025A, L"in",                                          L"autodesk.unit.symbol:in-1.0.1")                                       \
  PARAM_DEF(UST_ACRES,                                   0x000002BD, L"acres",                                       L"autodesk.unit.symbol:acres-1.0.1")                                    \
  PARAM_DEF(UST_HECTARES,                                0x00000321, L"hectare",                                     L"autodesk.unit.symbol:hectare-1.0.1")                                  \
  PARAM_DEF(UST_CY,                                      0x000003E9, L"CY",                                          L"autodesk.unit.symbol:cy-1.0.1")                                       \
  PARAM_DEF(UST_SF,                                      0x0000044D, L"SF",                                          L"autodesk.unit.symbol:sf-1.0.1")                                       \
  PARAM_DEF(UST_FT_SUP_2,                                0x0000044E, L"ft\u00B2",                                    L"autodesk.unit.symbol:ftSup2-1.0.1")                                   \
  PARAM_DEF(UST_FT_CARET_2,                              0x0000044F, L"ft^2",                                        L"autodesk.unit.symbol:ftCaret2-1.0.1")                                 \
  PARAM_DEF(UST_M_SUP_2,                                 0x000004B1, L"m\u00B2",                                     L"autodesk.unit.symbol:mSup2-1.0.1")                                    \
  PARAM_DEF(UST_M_CARET_2,                               0x000004B2, L"m^2",                                         L"autodesk.unit.symbol:mCaret2-1.0.1")                                  \
  PARAM_DEF(UST_CF,                                      0x00000515, L"CF",                                          L"autodesk.unit.symbol:cf-1.0.1")                                       \
  PARAM_DEF(UST_FT_SUP_3,                                0x00000516, L"ft\u00B3",                                    L"autodesk.unit.symbol:ftSup3-1.0.1")                                   \
  PARAM_DEF(UST_FT_CARET_3,                              0x00000517, L"ft^3",                                        L"autodesk.unit.symbol:ftCaret3-1.0.1")                                 \
  PARAM_DEF(UST_M_SUP_3,                                 0x00000579, L"m\u00B3",                                     L"autodesk.unit.symbol:mSup3-1.0.1")                                    \
  PARAM_DEF(UST_M_CARET_3,                               0x0000057A, L"m^3",                                         L"autodesk.unit.symbol:mCaret3-1.0.1")                                  \
  PARAM_DEF(UST_DEGREE_SYMBOL,                           0x000005DD, L"\u00B0",                                      L"autodesk.unit.symbol:degree-1.0.1")                                   \
  PARAM_DEF(UST_PERCENT_SIGN,                            0x0000076D, L"%",                                           L"autodesk.unit.symbol:percent-1.0.1")                                  \
  PARAM_DEF(UST_IN_SUP_2,                                0x000007D1, L"in\u00B2",                                    L"autodesk.unit.symbol:inSup2-1.0.1")                                   \
  PARAM_DEF(UST_IN_CARET_2,                              0x000007D2, L"in^2",                                        L"autodesk.unit.symbol:inCaret2-1.0.1")                                 \
  PARAM_DEF(UST_CM_SUP_2,                                0x00000835, L"cm\u00B2",                                    L"autodesk.unit.symbol:cmSup2-1.0.1")                                   \
  PARAM_DEF(UST_CM_CARET_2,                              0x00000836, L"cm^2",                                        L"autodesk.unit.symbol:cmCaret2-1.0.1")                                 \
  PARAM_DEF(UST_MM_SUP_2,                                0x00000899, L"mm\u00B2",                                    L"autodesk.unit.symbol:mmSup2-1.0.1")                                   \
  PARAM_DEF(UST_MM_CARET_2,                              0x0000089A, L"mm^2",                                        L"autodesk.unit.symbol:mmCaret2-1.0.1")                                 \
  PARAM_DEF(UST_IN_SUP_3,                                0x000008FD, L"in\u00B3",                                    L"autodesk.unit.symbol:inSup3-1.0.1")                                   \
  PARAM_DEF(UST_IN_CARET_3,                              0x000008FE, L"in^3",                                        L"autodesk.unit.symbol:inCaret3-1.0.1")                                 \
  PARAM_DEF(UST_CM_SUP_3,                                0x00000961, L"cm\u00B3",                                    L"autodesk.unit.symbol:cmSup3-1.0.1")                                   \
  PARAM_DEF(UST_CM_CARET_3,                              0x00000962, L"cm^3",                                        L"autodesk.unit.symbol:cmCaret3-1.0.1")                                 \
  PARAM_DEF(UST_MM_SUP_3,                                0x000009C5, L"mm\u00B3",                                    L"autodesk.unit.symbol:mmSup3-1.0.1")                                   \
  PARAM_DEF(UST_MM_CARET_3,                              0x000009C6, L"mm^3",                                        L"autodesk.unit.symbol:mmCaret3-1.0.1")                                 \
  PARAM_DEF(UST_L,                                       0x00000A29, L"L",                                           L"autodesk.unit.symbol:liter-1.0.1")                                    \
  PARAM_DEF(UST_GAL,                                     0x00000A8D, L"gal",                                         L"autodesk.unit.symbol:gal-1.0.1")                                      \
  PARAM_DEF(UST_KG_PER_CU_M,                             0x00000AF1, L"kg/m\u00B3",                                  L"autodesk.unit.symbol:kgPerMSup3-1.0.1")                               \
  PARAM_DEF(UST_LB_MASS_PER_CU_FT,                       0x00000B55, L"lb/ft\u00B3",                                 L"autodesk.unit.symbol:lbMassPerFtSup3-1.0.1")                          \
  PARAM_DEF(UST_LBM_PER_CU_FT,                           0x00000B56, L"lbm/ft\u00B3",                                L"autodesk.unit.symbol:lbmPerFtSup3-1.0.1")                             \
  PARAM_DEF(UST_LB_MASS_PER_CU_IN,                       0x00000BB9, L"lb/in\u00B3",                                 L"autodesk.unit.symbol:lbMassPerInSup3-1.0.1")                          \
  PARAM_DEF(UST_LBM_PER_CU_IN,                           0x00000BBA, L"lbm/in\u00B3",                                L"autodesk.unit.symbol:lbmPerInSup3-1.0.1")                             \
  PARAM_DEF(UST_BTU,                                     0x00000C1D, L"Btu",                                         L"autodesk.unit.symbol:btu-1.0.1")                                      \
  PARAM_DEF(UST_CAL,                                     0x00000C81, L"cal",                                         L"autodesk.unit.symbol:cal-1.0.1")                                      \
  PARAM_DEF(UST_KCAL,                                    0x00000CE5, L"kcal",                                        L"autodesk.unit.symbol:kcal-1.0.1")                                     \
  PARAM_DEF(UST_JOULE,                                   0x00000D49, L"J",                                           L"autodesk.unit.symbol:joule-1.0.1")                                    \
  PARAM_DEF(UST_KWH,                                     0x00000DAD, L"kWh",                                         L"autodesk.unit.symbol:kWh-1.0.1")                                      \
  PARAM_DEF(UST_THERM,                                   0x00000E11, L"therm",                                       L"autodesk.unit.symbol:therm-1.0.1")                                    \
  PARAM_DEF(UST_IN_WG_PER_100FT,                         0x00000E75, L"in-wg/100ft",                                 L"autodesk.unit.symbol:inDashWgPer100ft-1.0.1")                         \
  PARAM_DEF(UST_PASCAL_PER_M,                            0x00000ED9, L"Pa/m",                                        L"autodesk.unit.symbol:paPerM-1.0.1")                                   \
  PARAM_DEF(UST_WATT,                                    0x00000F3D, L"W",                                           L"autodesk.unit.symbol:watt-1.0.1")                                     \
  PARAM_DEF(UST_KILOWATT,                                0x00000FA1, L"kW",                                          L"autodesk.unit.symbol:kW-1.0.1")                                       \
  PARAM_DEF(UST_BTU_PER_S,                               0x00001005, L"Btu/s",                                       L"autodesk.unit.symbol:btuPerS-1.0.1")                                  \
  PARAM_DEF(UST_BTU_PER_H,                               0x00001069, L"Btu/h",                                       L"autodesk.unit.symbol:btuPerH-1.0.1")                                  \
  PARAM_DEF(UST_CAL_PER_S,                               0x000010CD, L"cal/s",                                       L"autodesk.unit.symbol:calPerS-1.0.1")                                  \
  PARAM_DEF(UST_KCAL_PER_S,                              0x00001131, L"kcal/s",                                      L"autodesk.unit.symbol:kcalPerS-1.0.1")                                 \
  PARAM_DEF(UST_WATT_PER_SQ_FT,                          0x00001195, L"W/ft\u00B2",                                  L"autodesk.unit.symbol:wPerFtSup2-1.0.1")                               \
  PARAM_DEF(UST_WATT_PER_SQ_M,                           0x000011F9, L"W/m\u00B2",                                   L"autodesk.unit.symbol:wPerMSup2-1.0.1")                                \
  PARAM_DEF(UST_IN_WG,                                   0x0000125D, L"in-wg",                                       L"autodesk.unit.symbol:inDashWg-1.0.1")                                 \
  PARAM_DEF(UST_PASCAL,                                  0x000012C1, L"Pa",                                          L"autodesk.unit.symbol:pa-1.0.1")                                       \
  PARAM_DEF(UST_KILOPASCAL,                              0x00001325, L"kPa",                                         L"autodesk.unit.symbol:kPa-1.0.1")                                      \
  PARAM_DEF(UST_MEGAPASCAL,                              0x00001389, L"MPa",                                         L"autodesk.unit.symbol:mPa-1.0.1")                                      \
  PARAM_DEF(UST_PSI,                                     0x000013ED, L"psi",                                         L"autodesk.unit.symbol:psi-1.0.1")                                      \
  PARAM_DEF(UST_LB_FORCE_PER_SQ_IN,                      0x000013EE, L"lb/in\u00B2",                                 L"autodesk.unit.symbol:lbForcePerInSup2-1.0.1")                         \
  PARAM_DEF(UST_PSIG,                                    0x000013EF, L"psig",                                        L"autodesk.unit.symbol:psig-1.0.1")                                     \
  PARAM_DEF(UST_PSIA,                                    0x000013F0, L"psia",                                        L"autodesk.unit.symbol:psia-1.0.1")                                     \
  PARAM_DEF(UST_LBF_PER_SQ_IN,                           0x000013F1, L"lbf/in\u00B2",                                L"autodesk.unit.symbol:lbfPerInSup2-1.0.1")                             \
  PARAM_DEF(UST_IN_HG,                                   0x00001451, L"inHg",                                        L"autodesk.unit.symbol:inHg-1.0.1")                                     \
  PARAM_DEF(UST_MM_HG,                                   0x000014B5, L"mmHg",                                        L"autodesk.unit.symbol:mmHg-1.0.1")                                     \
  PARAM_DEF(UST_ATM,                                     0x00001519, L"atm",                                         L"autodesk.unit.symbol:atm-1.0.1")                                      \
  PARAM_DEF(UST_BAR,                                     0x0000157D, L"bar",                                         L"autodesk.unit.symbol:bar-1.0.1")                                      \
  PARAM_DEF(UST_DEGREE_F,                                0x000015E1, L"\u00B0F",                                     L"autodesk.unit.symbol:degreeF-1.0.1")                                  \
  PARAM_DEF(UST_DEGREE_C,                                0x00001645, L"\u00B0C",                                     L"autodesk.unit.symbol:degreeC-1.0.1")                                  \
  PARAM_DEF(UST_KELVIN,                                  0x000016A9, L"K",                                           L"autodesk.unit.symbol:kelvin-1.0.0")                                   \
  PARAM_DEF(UST_DEGREE_R,                                0x0000170D, L"\u00B0R",                                     L"autodesk.unit.symbol:degreeR-1.0.1")                                  \
  PARAM_DEF(UST_FT_PER_MIN,                              0x00001771, L"ft/min",                                      L"autodesk.unit.symbol:ftPerMin-1.0.1")                                 \
  PARAM_DEF(UST_FPM,                                     0x00001772, L"FPM",                                         L"autodesk.unit.symbol:fpm-1.0.1")                                      \
  PARAM_DEF(UST_M_PER_S,                                 0x000017D5, L"m/s",                                         L"autodesk.unit.symbol:mPerS-1.0.1")                                    \
  PARAM_DEF(UST_CM_PER_MIN,                              0x00001839, L"cm/min",                                      L"autodesk.unit.symbol:cmPerMin-1.0.1")                                 \
  PARAM_DEF(UST_CU_FT_PER_MIN,                           0x0000189D, L"ft\u00B3/min",                                L"autodesk.unit.symbol:ftSup3PerMin-1.0.1")                             \
  PARAM_DEF(UST_CFM,                                     0x0000189E, L"CFM",                                         L"autodesk.unit.symbol:cfm-1.0.1")                                      \
  PARAM_DEF(UST_L_PER_S,                                 0x00001901, L"L/s",                                         L"autodesk.unit.symbol:lPerS-1.0.1")                                    \
  PARAM_DEF(UST_LPS,                                     0x00001902, L"LPS",                                         L"autodesk.unit.symbol:lps-1.0.1")                                      \
  PARAM_DEF(UST_CU_M_PER_S,                              0x00001965, L"m\u00B3/s",                                   L"autodesk.unit.symbol:mSup3PerS-1.0.1")                                \
  PARAM_DEF(UST_CMS,                                     0x00001966, L"CMS",                                         L"autodesk.unit.symbol:cms-1.0.1")                                      \
  PARAM_DEF(UST_CU_M_PER_H,                              0x000019C9, L"m\u00B3/h",                                   L"autodesk.unit.symbol:mSup3PerH-1.0.1")                                \
  PARAM_DEF(UST_CMH,                                     0x000019CA, L"CMH",                                         L"autodesk.unit.symbol:cmh-1.0.1")                                      \
  PARAM_DEF(UST_GAL_PER_MIN,                             0x00001A2D, L"gal/min",                                     L"autodesk.unit.symbol:galPerMin-1.0.1")                                \
  PARAM_DEF(UST_GPM,                                     0x00001A2E, L"GPM",                                         L"autodesk.unit.symbol:gpm-1.0.1")                                      \
  PARAM_DEF(UST_USGPM,                                   0x00001A2F, L"usgpm",                                       L"autodesk.unit.symbol:usgpm-1.0.1")                                    \
  PARAM_DEF(UST_GAL_PER_H,                               0x00001A91, L"gal/h",                                       L"autodesk.unit.symbol:galPerH-1.0.1")                                  \
  PARAM_DEF(UST_GPH,                                     0x00001A92, L"GPH",                                         L"autodesk.unit.symbol:gph-1.0.1")                                      \
  PARAM_DEF(UST_USGPH,                                   0x00001A93, L"usgph",                                       L"autodesk.unit.symbol:usgph-1.0.1")                                    \
  PARAM_DEF(UST_AMPERE,                                  0x00001AF5, L"A",                                           L"autodesk.unit.symbol:ampere-1.0.0")                                   \
  PARAM_DEF(UST_KILOAMPERE,                              0x00001B59, L"kA",                                          L"autodesk.unit.symbol:kA-1.0.1")                                       \
  PARAM_DEF(UST_MILLIAMPERE,                             0x00001BBD, L"mA",                                          L"autodesk.unit.symbol:mA-1.0.1")                                       \
  PARAM_DEF(UST_VOLT,                                    0x00001C21, L"V",                                           L"autodesk.unit.symbol:volt-1.0.1")                                     \
  PARAM_DEF(UST_KILOVOLT,                                0x00001C85, L"kV",                                          L"autodesk.unit.symbol:kV-1.0.1")                                       \
  PARAM_DEF(UST_MILLIVOLT,                               0x00001CE9, L"mV",                                          L"autodesk.unit.symbol:mV-1.0.1")                                       \
  PARAM_DEF(UST_HZ,                                      0x00001D4D, L"Hz",                                          L"autodesk.unit.symbol:hz-1.0.1")                                       \
  PARAM_DEF(UST_CPS,                                     0x00001DB1, L"cps",                                         L"autodesk.unit.symbol:cps-1.0.1")                                      \
  PARAM_DEF(UST_LX,                                      0x00001E15, L"lx",                                          L"autodesk.unit.symbol:lx-1.0.1")                                       \
  PARAM_DEF(UST_FC,                                      0x00001E79, L"fc",                                          L"autodesk.unit.symbol:fc-1.0.1")                                       \
  PARAM_DEF(UST_FTC,                                     0x00001E7A, L"Ftc",                                         L"autodesk.unit.symbol:ftc-1.0.1")                                      \
  PARAM_DEF(UST_FL,                                      0x00001EDD, L"fL",                                          L"autodesk.unit.symbol:fL-1.0.1")                                       \
  PARAM_DEF(UST_FL_LOWERCASE,                            0x00001EDE, L"fl",                                          L"autodesk.unit.symbol:flLowercase-1.0.1")                              \
  PARAM_DEF(UST_FTL,                                     0x00001EDF, L"ftL",                                         L"autodesk.unit.symbol:ftL-1.0.1")                                      \
  PARAM_DEF(UST_CD_PER_SQ_M,                             0x00001F41, L"cd/m\u00B2",                                  L"autodesk.unit.symbol:cdPerMSup2-1.0.1")                               \
  PARAM_DEF(UST_CD,                                      0x00001FA5, L"cd",                                          L"autodesk.unit.symbol:cd-1.0.0")                                       \
  PARAM_DEF(UST_LM,                                      0x0000206D, L"lm",                                          L"autodesk.unit.symbol:lm-1.0.1")                                       \
  PARAM_DEF(UST_VOLTAMPERE,                              0x000020D1, L"VA",                                          L"autodesk.unit.symbol:vA-1.0.1")                                       \
  PARAM_DEF(UST_KILOVOLTAMPERE,                          0x00002135, L"kVA",                                         L"autodesk.unit.symbol:kVA-1.0.1")                                      \
  PARAM_DEF(UST_HP,                                      0x00002199, L"hp",                                          L"autodesk.unit.symbol:hp-1.0.1")                                       \
  PARAM_DEF(UST_N,                                       0x000021FD, L"N",                                           L"autodesk.unit.symbol:newton-1.0.1")                                   \
  PARAM_DEF(UST_DA_N,                                    0x00002261, L"daN",                                         L"autodesk.unit.symbol:daN-1.0.1")                                      \
  PARAM_DEF(UST_K_N,                                     0x000022C5, L"kN",                                          L"autodesk.unit.symbol:kN-1.0.1")                                       \
  PARAM_DEF(UST_M_N,                                     0x00002329, L"MN",                                          L"autodesk.unit.symbol:mN-1.0.1")                                       \
  PARAM_DEF(UST_KIP,                                     0x0000238D, L"kip",                                         L"autodesk.unit.symbol:kip-1.0.1")                                      \
  PARAM_DEF(UST_KGF,                                     0x000023F1, L"kgf",                                         L"autodesk.unit.symbol:kgf-1.0.1")                                      \
  PARAM_DEF(UST_TF,                                      0x00002455, L"Tf",                                          L"autodesk.unit.symbol:tf-1.0.1")                                       \
  PARAM_DEF(UST_LB_FORCE,                                0x000024B9, L"lb",                                          L"autodesk.unit.symbol:lbForce-1.0.1")                                  \
  PARAM_DEF(UST_LBF,                                     0x000024BA, L"lbf",                                         L"autodesk.unit.symbol:lbf-1.0.1")                                      \
  PARAM_DEF(UST_N_PER_M,                                 0x0000251D, L"N/m",                                         L"autodesk.unit.symbol:nPerM-1.0.1")                                    \
  PARAM_DEF(UST_DA_N_PER_M,                              0x00002581, L"daN/m",                                       L"autodesk.unit.symbol:daNPerM-1.0.1")                                  \
  PARAM_DEF(UST_K_N_PER_M,                               0x000025E5, L"kN/m",                                        L"autodesk.unit.symbol:kNPerM-1.0.1")                                   \
  PARAM_DEF(UST_M_N_PER_M,                               0x00002649, L"MN/m",                                        L"autodesk.unit.symbol:mNPerM-1.0.1")                                   \
  PARAM_DEF(UST_KIP_PER_FT,                              0x000026AD, L"kip/ft",                                      L"autodesk.unit.symbol:kipPerFt-1.0.1")                                 \
  PARAM_DEF(UST_KGF_PER_M,                               0x00002711, L"kgf/m",                                       L"autodesk.unit.symbol:kgfPerM-1.0.1")                                  \
  PARAM_DEF(UST_TF_PER_M,                                0x00002775, L"Tf/m",                                        L"autodesk.unit.symbol:tfPerM-1.0.1")                                   \
  PARAM_DEF(UST_LB_FORCE_PER_FT,                         0x000027D9, L"lb/ft",                                       L"autodesk.unit.symbol:lbForcePerFt-1.0.1")                             \
  PARAM_DEF(UST_LBF_PER_FT,                              0x000027DA, L"lbf/ft",                                      L"autodesk.unit.symbol:lbfPerFt-1.0.1")                                 \
  PARAM_DEF(UST_N_PER_M_SUP_2,                           0x0000283D, L"N/m\u00B2",                                   L"autodesk.unit.symbol:nPerMSup2-1.0.1")                                \
  PARAM_DEF(UST_DA_N_PER_M_SUP_2,                        0x000028A1, L"daN/m\u00B2",                                 L"autodesk.unit.symbol:daNPerMSup2-1.0.1")                              \
  PARAM_DEF(UST_K_N_PER_M_SUP_2,                         0x00002905, L"kN/m\u00B2",                                  L"autodesk.unit.symbol:kNPerMSup2-1.0.1")                               \
  PARAM_DEF(UST_M_N_PER_M_SUP_2,                         0x00002969, L"MN/m\u00B2",                                  L"autodesk.unit.symbol:mNPerMSup2-1.0.1")                               \
  PARAM_DEF(UST_KSF,                                     0x000029CD, L"ksf",                                         L"autodesk.unit.symbol:ksf-1.0.1")                                      \
  PARAM_DEF(UST_KIP_PER_SQ_FT,                           0x000029CE, L"kip/ft\u00B2",                                L"autodesk.unit.symbol:kipPerFtSup2-1.0.1")                             \
  PARAM_DEF(UST_KGF_PER_M_SUP_2,                         0x00002A31, L"kgf/m\u00B2",                                 L"autodesk.unit.symbol:kgfPerMSup2-1.0.1")                              \
  PARAM_DEF(UST_TF_PER_M_SUP_2,                          0x00002A95, L"Tf/m\u00B2",                                  L"autodesk.unit.symbol:tfPerMSup2-1.0.1")                               \
  PARAM_DEF(UST_PSF,                                     0x00002AF9, L"psf",                                         L"autodesk.unit.symbol:psf-1.0.1")                                      \
  PARAM_DEF(UST_LB_FORCE_PER_SQ_FT,                      0x00002AFA, L"lb/ft\u00B2",                                 L"autodesk.unit.symbol:lbForcePerFtSup2-1.0.1")                         \
  PARAM_DEF(UST_LBF_PER_SQ_FT,                           0x00002AFB, L"lbf/ft\u00B2",                                L"autodesk.unit.symbol:lbfPerFtSup2-1.0.1")                             \
  PARAM_DEF(UST_N_DASH_M,                                0x00002B5D, L"N-m",                                         L"autodesk.unit.symbol:nDashM-1.0.1")                                   \
  PARAM_DEF(UST_DA_N_DASH_M,                             0x00002BC1, L"daN-m",                                       L"autodesk.unit.symbol:daNDashM-1.0.1")                                 \
  PARAM_DEF(UST_K_N_DASH_M,                              0x00002C25, L"kN-m",                                        L"autodesk.unit.symbol:kNDashM-1.0.1")                                  \
  PARAM_DEF(UST_M_N_DASH_M,                              0x00002C89, L"MN-m",                                        L"autodesk.unit.symbol:mNDashM-1.0.1")                                  \
  PARAM_DEF(UST_KIP_DASH_FT,                             0x00002CED, L"kip-ft",                                      L"autodesk.unit.symbol:kipDashFt-1.0.1")                                \
  PARAM_DEF(UST_KGF_DASH_M,                              0x00002D51, L"kgf-m",                                       L"autodesk.unit.symbol:kgfDashM-1.0.1")                                 \
  PARAM_DEF(UST_TF_DASH_M,                               0x00002DB5, L"Tf-m",                                        L"autodesk.unit.symbol:tfDashM-1.0.1")                                  \
  PARAM_DEF(UST_LB_FORCE_DASH_FT,                        0x00002E19, L"lb-ft",                                       L"autodesk.unit.symbol:lbForceDashFt-1.0.1")                            \
  PARAM_DEF(UST_LBF_DASH_FT,                             0x00002E1A, L"lbf-ft",                                      L"autodesk.unit.symbol:lbfDashFt-1.0.1")                                \
  PARAM_DEF(UST_M_PER_K_N,                               0x00002E7D, L"m/kN",                                        L"autodesk.unit.symbol:mPerKN-1.0.0")                                   \
  PARAM_DEF(UST_FT_PER_KIP,                              0x00002EE1, L"ft/kip",                                      L"autodesk.unit.symbol:ftPerKip-1.0.0")                                 \
  PARAM_DEF(UST_M_SUP_2_PER_K_N,                         0x00002F45, L"m\u00B2/kN",                                  L"autodesk.unit.symbol:mSup2PerKN-1.0.1")                               \
  PARAM_DEF(UST_FT_SUP_2_PER_KIP,                        0x00002FA9, L"ft\u00B2/kip",                                L"autodesk.unit.symbol:ftSup2PerKip-1.0.1")                             \
  PARAM_DEF(UST_M_SUP_3_PER_K_N,                         0x0000300D, L"m\u00B3/kN",                                  L"autodesk.unit.symbol:mSup3PerKN-1.0.1")                               \
  PARAM_DEF(UST_FT_SUP_3_PER_KIP,                        0x00003071, L"ft\u00B3/kip",                                L"autodesk.unit.symbol:ftSup3PerKip-1.0.1")                             \
  PARAM_DEF(UST_INV_K_N,                                 0x000030D5, L"1/kN",                                        L"autodesk.unit.symbol:invKN-1.0.0")                                    \
  PARAM_DEF(UST_INV_KIP,                                 0x00003139, L"1/kip",                                       L"autodesk.unit.symbol:invKip-1.0.0")                                   \
  PARAM_DEF(UST_FTH2O_PER_100FT,                         0x0000319D, L"ftH2O/100ft",                                 L"autodesk.unit.symbol:ftH2OPer100ft-1.0.1")                            \
  PARAM_DEF(UST_FT_OF_WATER_PER_100FT,                   0x0000319E, L"FT/100ft",                                    L"autodesk.unit.symbol:ftOfWaterPer100ft-1.0.1")                        \
  PARAM_DEF(UST_FEET_OF_WATER_PER_100FT,                 0x0000319F, L"Feet/100ft",                                  L"autodesk.unit.symbol:feetOfWaterPer100ft-1.0.1")                      \
  PARAM_DEF(UST_FTH2O,                                   0x00003201, L"ftH2O",                                       L"autodesk.unit.symbol:ftH2O-1.0.1")                                    \
  PARAM_DEF(UST_FT_OF_WATER,                             0x00003202, L"FT",                                          L"autodesk.unit.symbol:ftOfWater-1.0.1")                                \
  PARAM_DEF(UST_FEET_OF_WATER,                           0x00003203, L"Feet",                                        L"autodesk.unit.symbol:feetOfWater-1.0.1")                              \
  PARAM_DEF(UST_PA_S,                                    0x00003265, L"Pa-s",                                        L"autodesk.unit.symbol:paDashS-1.0.1")                                  \
  PARAM_DEF(UST_LB_FORCE_PER_FT_S,                       0x000032C9, L"lb/ft-s",                                     L"autodesk.unit.symbol:lbMassPerFtDashS-1.0.1")                         \
  PARAM_DEF(UST_LBM_PER_FT_S,                            0x000032CA, L"lbm/ft-s",                                    L"autodesk.unit.symbol:lbmPerFtDashS-1.0.1")                            \
  PARAM_DEF(UST_CP,                                      0x0000332D, L"cP",                                          L"autodesk.unit.symbol:cP-1.0.1")                                       \
  PARAM_DEF(UST_FT_PER_S,                                0x00003391, L"ft/s",                                        L"autodesk.unit.symbol:ftPerS-1.0.1")                                   \
  PARAM_DEF(UST_FPS,                                     0x00003392, L"FPS",                                         L"autodesk.unit.symbol:fps-1.0.1")                                      \
  PARAM_DEF(UST_KSI,                                     0x000033F5, L"ksi",                                         L"autodesk.unit.symbol:ksi-1.0.1")                                      \
  PARAM_DEF(UST_KIP_PER_SQ_IN,                           0x000033F6, L"kip/in\u00B2",                                L"autodesk.unit.symbol:kipPerInSup2-1.0.1")                             \
  PARAM_DEF(UST_KN_PER_M_SUP_3,                          0x00003459, L"kN/m\u00B3",                                  L"autodesk.unit.symbol:kNPerMSup3-1.0.1")                               \
  PARAM_DEF(UST_LB_FORCE_PER_CU_FT,                      0x000034BD, L"lb/ft\u00B3",                                 L"autodesk.unit.symbol:lbForcePerFtSup3-1.0.1")                         \
  PARAM_DEF(UST_LBF_PER_CU_FT,                           0x000034BE, L"lbf/ft\u00B3",                                L"autodesk.unit.symbol:lbfPerFtSup3-1.0.1")                             \
  PARAM_DEF(UST_KIP_PER_IN_SUP_3,                        0x00003521, L"kip/in\u00B3",                                L"autodesk.unit.symbol:kipPerInSup3-1.0.1")                             \
  PARAM_DEF(UST_INV_DEGREE_F,                            0x00003585, L"1/\u00B0F",                                   L"autodesk.unit.symbol:invDegreeF-1.0.1")                               \
  PARAM_DEF(UST_INV_DEGREE_C,                            0x000035E9, L"1/\u00B0C",                                   L"autodesk.unit.symbol:invDegreeC-1.0.1")                               \
  PARAM_DEF(UST_N_DASH_M_PER_M,                          0x0000364D, L"N-m/m",                                       L"autodesk.unit.symbol:nDashMPerM-1.0.1")                               \
  PARAM_DEF(UST_DA_N_DASH_M_PER_M,                       0x000036B1, L"daN-m/m",                                     L"autodesk.unit.symbol:daNDashMPerM-1.0.1")                             \
  PARAM_DEF(UST_K_N_DASH_M_PER_M,                        0x00003715, L"kN-m/m",                                      L"autodesk.unit.symbol:kNDashMPerM-1.0.1")                              \
  PARAM_DEF(UST_M_N_DASH_M_PER_M,                        0x00003779, L"MN-m/m",                                      L"autodesk.unit.symbol:mNDashMPerM-1.0.1")                              \
  PARAM_DEF(UST_KIP_DASH_FT_PER_FT,                      0x000037DD, L"kip-ft/ft",                                   L"autodesk.unit.symbol:kipDashFtPerFt-1.0.1")                           \
  PARAM_DEF(UST_KGF_DASH_M_PER_M,                        0x00003841, L"kgf-m/m",                                     L"autodesk.unit.symbol:kgfDashMPerM-1.0.1")                             \
  PARAM_DEF(UST_TF_DASH_M_PER_M,                         0x000038A5, L"Tf-m/m",                                      L"autodesk.unit.symbol:tfDashMPerM-1.0.1")                              \
  PARAM_DEF(UST_LB_FORCE_DASH_FT_PER_FT,                 0x00003909, L"lb-ft/ft",                                    L"autodesk.unit.symbol:lbForceDashFtPerFt-1.0.1")                       \
  PARAM_DEF(UST_LBF_DASH_FT_PER_FT,                      0x0000390A, L"lbf-ft/ft",                                   L"autodesk.unit.symbol:lbfDashFtPerFt-1.0.1")                           \
  PARAM_DEF(UST_LB_FORCE_PER_FT_H,                       0x0000396D, L"lb/ft-h",                                     L"autodesk.unit.symbol:lbMassPerFtDashH-1.0.1")                         \
  PARAM_DEF(UST_LBM_PER_FT_H,                            0x0000396E, L"lbm/ft-h",                                    L"autodesk.unit.symbol:lbmPerFtDashH-1.0.1")                            \
  PARAM_DEF(UST_KIPS_PER_IN,                             0x000039D1, L"kip/in",                                      L"autodesk.unit.symbol:kipPerIn-1.0.1")                                 \
  PARAM_DEF(UST_KIPS_PER_CU_FT,                          0x00003A35, L"kip/ft\u00B3",                                L"autodesk.unit.symbol:kipPerFtSup3-1.0.1")                             \
  PARAM_DEF(UST_KIP_FT_PER_DEGREE,                       0x00003A99, L"kip-ft/\u00B0",                               L"autodesk.unit.symbol:kipDashFtPerDegree-1.0.1")                       \
  PARAM_DEF(UST_K_N_M_PER_DEGREE,                        0x00003AFD, L"kN-m/\u00B0",                                 L"autodesk.unit.symbol:kNDashMPerDegree-1.0.1")                         \
  PARAM_DEF(UST_KIP_FT_PER_DEGREE_PER_FT,                0x00003B61, L"kip-ft/\u00B0/ft",                            L"autodesk.unit.symbol:kipDashFtPerDegreePerFt-1.0.1")                  \
  PARAM_DEF(UST_K_N_M_PER_DEGREE_PER_M,                  0x00003BC5, L"kN-m/\u00B0/m",                               L"autodesk.unit.symbol:kNDashMPerDegreePerM-1.0.1")                     \
  PARAM_DEF(UST_WATT_PER_SQ_M_K,                         0x00003C29, L"W/(m\u00B2\u00B7K)",                          L"autodesk.unit.symbol:wPerMSup2K-1.0.1")                               \
  PARAM_DEF(UST_BTU_PER_H_SQ_FT_DEGREE_F,                0x00003C8D, L"BTU/(h\u00B7ft\u00B2\u00B7\u00B0F)",          L"autodesk.unit.symbol:btuPerHFtSup2DegreeF-1.0.1")                     \
  PARAM_DEF(UST_CFM_PER_SQ_FT,                           0x00003CF1, L"CFM/ft\u00B2",                                L"autodesk.unit.symbol:cfmPerFtSup2-1.0.1")                             \
  PARAM_DEF(UST_CFM_PER_SF,                              0x00003CF2, L"CFM/SF",                                      L"autodesk.unit.symbol:cfmPerSf-1.0.1")                                 \
  PARAM_DEF(UST_LPS_PER_SQ_M,                            0x00003D55, L"LPS/m\u00B2",                                 L"autodesk.unit.symbol:lpsPerMSup2-1.0.1")                              \
  PARAM_DEF(UST_L_PER_S_SQ_M,                            0x00003D56, L"L/(s\u00B7m\u00B2)",                          L"autodesk.unit.symbol:lPerSMSup2-1.0.1")                               \
  PARAM_DEF(UST_COLON_10,                                0x00003DB9, L":10",                                         L"autodesk.unit.symbol:colon10-1.0.1")                                  \
  PARAM_DEF(UST_COLON_12,                                0x00003E1D, L":12",                                         L"autodesk.unit.symbol:colon12-1.0.1")                                  \
  PARAM_DEF(UST_SLOPE_DEGREE_SYMBOL,                     0x00003E81, L"\u00B0",                                      L"autodesk.unit.symbol:slopeDegree-1.0.0")                              \
  PARAM_DEF(UST_WATT_PER_CU_FT,                          0x00004011, L"W/ft\u00B3",                                  L"autodesk.unit.symbol:wPerFtSup3-1.0.1")                               \
  PARAM_DEF(UST_WATT_PER_CU_M,                           0x00004075, L"W/m\u00B3",                                   L"autodesk.unit.symbol:wPerMSup3-1.0.1")                                \
  PARAM_DEF(UST_BTU_PER_H_SQ_FT,                         0x000040D9, L"Btu/(h\u00B7ft\u00B2)",                       L"autodesk.unit.symbol:btuPerHFtSup2-1.0.1")                            \
  PARAM_DEF(UST_BTU_PER_H_CU_FT,                         0x0000413D, L"Btu/(h\u00B7ft\u00B3)",                       L"autodesk.unit.symbol:btuPerHFtSup3-1.0.1")                            \
  PARAM_DEF(UST_TON,                                     0x000041A1, L"ton",                                         L"autodesk.unit.symbol:ton-1.0.1")                                      \
  PARAM_DEF(UST_TON_OF_REFRIGERATION,                    0x000041A2, L"ton of refrigeration",                        L"autodesk.unit.symbol:tonOfRefrigeration-1.0.1")                       \
  PARAM_DEF(UST_CFM_PER_CU_FT,                           0x00004205, L"CFM/ft\u00B3",                                L"autodesk.unit.symbol:cfmPerFtSup3-1.0.1")                             \
  PARAM_DEF(UST_CFM_PER_CF,                              0x00004206, L"CFM/CF",                                      L"autodesk.unit.symbol:cfmPerCf-1.0.1")                                 \
  PARAM_DEF(UST_L_PER_S_CU_M,                            0x00004269, L"L/(s\u00B7m\u00B3)",                          L"autodesk.unit.symbol:lPerSMSup3-1.0.1")                               \
  PARAM_DEF(UST_CFM_PER_TON,                             0x000042CD, L"CFM/ton",                                     L"autodesk.unit.symbol:cfmPerTon-1.0.1")                                \
  PARAM_DEF(UST_L_PER_S_KW,                              0x00004331, L"L/(s\u00B7kW)",                               L"autodesk.unit.symbol:lPerSKw-1.0.1")                                  \
  PARAM_DEF(UST_SQ_FT_PER_TON,                           0x00004395, L"ft\u00B2/ton",                                L"autodesk.unit.symbol:ftSup2PerTon-1.0.1")                             \
  PARAM_DEF(UST_SF_PER_TON,                              0x00004396, L"SF/ton",                                      L"autodesk.unit.symbol:sfPerTon-1.0.1")                                 \
  PARAM_DEF(UST_SQ_M_PER_KW,                             0x000043F9, L"m\u00B2/kW",                                  L"autodesk.unit.symbol:mSup2PerKw-1.0.1")                               \
  PARAM_DEF(UST_DOLLAR,                                  0x0000445D, L"\u0024",                                      L"autodesk.unit.symbol:usDollar-1.0.0")                                 \
  PARAM_DEF(UST_EURO_SUFFIX,                             0x0000445E, L"\u20AC",                                      L"autodesk.unit.symbol:euroSuffix-1.0.0")                               \
  PARAM_DEF(UST_EURO_PREFIX,                             0x0000445F, L"\u20AC",                                      L"autodesk.unit.symbol:euroPrefix-1.0.0")                               \
  PARAM_DEF(UST_POUND,                                   0x00004460, L"\u00A3",                                      L"autodesk.unit.symbol:ukPound-1.0.0")                                  \
  PARAM_DEF(UST_YEN,                                     0x00004461, L"\u00A5",                                      L"autodesk.unit.symbol:yen-1.0.0")                                      \
  PARAM_DEF(UST_CHINESE_HONG_KONG_SAR,                   0x00004462, L"HK\u0024",                                    L"autodesk.unit.symbol:chineseHongKongDollar-1.0.0")                    \
  PARAM_DEF(UST_WON,                                     0x00004463, L"\u20A9",                                      L"autodesk.unit.symbol:won-1.0.0")                                      \
  PARAM_DEF(UST_SHEQEL,                                  0x00004464, L"\u20AA",                                      L"autodesk.unit.symbol:shekel-1.0.0")                                   \
  PARAM_DEF(UST_DONG,                                    0x00004465, L"\u20AB",                                      L"autodesk.unit.symbol:dong-1.0.0")                                     \
  PARAM_DEF(UST_BAHT,                                    0x00004466, L"\u0E3F",                                      L"autodesk.unit.symbol:baht-1.0.0")                                     \
  PARAM_DEF(UST_KRONER,                                  0x00004467, L"kr",                                          L"autodesk.unit.symbol:krone-1.0.0")                                    \
  PARAM_DEF(UST_LM_PER_W,                                0x000044C1, L"lm/W",                                        L"autodesk.unit.symbol:lmPerW-1.0.1")                                   \
  PARAM_DEF(UST_SF_PER_MBH,                              0x00004525, L"SF/MBh",                                      L"autodesk.unit.symbol:sfPerMbh-1.0.1")                                 \
  PARAM_DEF(UST_SF_PER_KBTU_PER_H,                       0x00004526, L"SF\u00B7h/kBtu",                              L"autodesk.unit.symbol:sfHPerKbtu-1.0.1")                               \
  PARAM_DEF(UST_SQ_FT_PER_MBH,                           0x00004527, L"ft\u00B2/MBh",                                L"autodesk.unit.symbol:ftSup2PerMbh-1.0.1")                             \
  PARAM_DEF(UST_SQ_FT_PER_KBTU_PER_H,                    0x00004528, L"ft\u00B2\u00B7h/kBtu",                        L"autodesk.unit.symbol:ftSup2HPerKbtu-1.0.1")                           \
  PARAM_DEF(UST_K_N_PER_CM_SUP_2,                        0x00004589, L"kN/cm\u00B2",                                 L"autodesk.unit.symbol:kNPerCmSup2-1.0.1")                              \
  PARAM_DEF(UST_N_PER_MM_SUP_2,                          0x000045ED, L"N/mm\u00B2",                                  L"autodesk.unit.symbol:nPerMmSup2-1.0.1")                               \
  PARAM_DEF(UST_K_N_PER_MM_SUP_2,                        0x00004651, L"kN/mm\u00B2",                                 L"autodesk.unit.symbol:kNPerMmSup2-1.0.1")                              \
  PARAM_DEF(UST_ONE_COLON,                               0x00004719, L"1:",                                          L"autodesk.unit.symbol:1Colon-1.0.1")                                   \
  PARAM_DEF(UST_H_SQ_FT_DEGREE_F_PER_BTU,                0x000047E1, L"(h\u00B7ft\u00B2\u00B7\u00B0F)/BTU",          L"autodesk.unit.symbol:hFtSup2DegreeFPerBtu-1.0.1")                     \
  PARAM_DEF(UST_SQ_M_K_PER_WATT,                         0x00004845, L"(m\u00B2\u00B7K)/W",                          L"autodesk.unit.symbol:mSup2KPerW-1.0.1")                               \
  PARAM_DEF(UST_BTU_PER_F,                               0x000048A9, L"BTU/\u00B0F",                                 L"autodesk.unit.symbol:btuPerDegreeF-1.0.1")                            \
  PARAM_DEF(UST_J_PER_KELVIN,                            0x0000490D, L"J/K",                                         L"autodesk.unit.symbol:jPerK-1.0.1")                                    \
  PARAM_DEF(UST_KJ_PER_KELVIN,                           0x00004971, L"kJ/K",                                        L"autodesk.unit.symbol:kJPerK-1.0.1")                                   \
  PARAM_DEF(UST_KGM,                                     0x000049D5, L"kg",                                          L"autodesk.unit.symbol:kg-1.0.0")                                       \
  PARAM_DEF(UST_TM,                                      0x00004A39, L"t",                                           L"autodesk.unit.symbol:tonne-1.0.1")                                    \
  PARAM_DEF(UST_LB_MASS,                                 0x00004A9D, L"lb",                                          L"autodesk.unit.symbol:lbMass-1.0.1")                                   \
  PARAM_DEF(UST_LBM,                                     0x00004A9E, L"lbm",                                         L"autodesk.unit.symbol:lbm-1.0.1")                                      \
  PARAM_DEF(UST_M_PER_SQ_S,                              0x00004B01, L"m/s\u00B2",                                   L"autodesk.unit.symbol:mPerSSup2-1.0.1")                                \
  PARAM_DEF(UST_KM_PER_SQ_S,                             0x00004B65, L"km/s\u00B2",                                  L"autodesk.unit.symbol:kmPerSSup2-1.0.1")                               \
  PARAM_DEF(UST_IN_PER_SQ_S,                             0x00004BC9, L"in/s\u00B2",                                  L"autodesk.unit.symbol:inPerSSup2-1.0.1")                               \
  PARAM_DEF(UST_FT_PER_SQ_S,                             0x00004C2D, L"ft/s\u00B2",                                  L"autodesk.unit.symbol:ftPerSSup2-1.0.1")                               \
  PARAM_DEF(UST_MI_PER_SQ_S,                             0x00004C91, L"mi/s\u00B2",                                  L"autodesk.unit.symbol:miPerSSup2-1.0.1")                               \
  PARAM_DEF(UST_FT_SUP_4,                                0x00004CF5, L"ft\u2074",                                    L"autodesk.unit.symbol:ftSup4-1.0.1")                                   \
  PARAM_DEF(UST_IN_SUP_4,                                0x00004D59, L"in\u2074",                                    L"autodesk.unit.symbol:inSup4-1.0.1")                                   \
  PARAM_DEF(UST_MM_SUP_4,                                0x00004DBD, L"mm\u2074",                                    L"autodesk.unit.symbol:mmSup4-1.0.1")                                   \
  PARAM_DEF(UST_CM_SUP_4,                                0x00004E21, L"cm\u2074",                                    L"autodesk.unit.symbol:cmSup4-1.0.1")                                   \
  PARAM_DEF(UST_M_SUP_4,                                 0x00004E85, L"m\u2074",                                     L"autodesk.unit.symbol:mSup4-1.0.1")                                    \
  PARAM_DEF(UST_FT_SUP_6,                                0x00004EE9, L"ft\u2076",                                    L"autodesk.unit.symbol:ftSup6-1.0.1")                                   \
  PARAM_DEF(UST_IN_SUP_6,                                0x00004F4D, L"in\u2076",                                    L"autodesk.unit.symbol:inSup6-1.0.1")                                   \
  PARAM_DEF(UST_MM_SUP_6,                                0x00004FB1, L"mm\u2076",                                    L"autodesk.unit.symbol:mmSup6-1.0.1")                                   \
  PARAM_DEF(UST_CM_SUP_6,                                0x00005015, L"cm\u2076",                                    L"autodesk.unit.symbol:cmSup6-1.0.1")                                   \
  PARAM_DEF(UST_M_SUP_6,                                 0x00005079, L"m\u2076",                                     L"autodesk.unit.symbol:mSup6-1.0.1")                                    \
  PARAM_DEF(UST_SQ_FT_PER_FT,                            0x000050DD, L"ft\u00B2/ft",                                 L"autodesk.unit.symbol:ftSup2PerFt-1.0.1")                              \
  PARAM_DEF(UST_SQ_IN_PER_FT,                            0x00005141, L"in\u00B2/ft",                                 L"autodesk.unit.symbol:inSup2PerFt-1.0.1")                              \
  PARAM_DEF(UST_SQ_MM_PER_M,                             0x000051A5, L"mm\u00B2/m",                                  L"autodesk.unit.symbol:mmSup2PerM-1.0.1")                               \
  PARAM_DEF(UST_SQ_CM_PER_M,                             0x00005209, L"cm\u00B2/m",                                  L"autodesk.unit.symbol:cmSup2PerM-1.0.1")                               \
  PARAM_DEF(UST_SQ_M_PER_M,                              0x0000526D, L"m\u00B2/m",                                   L"autodesk.unit.symbol:mSup2PerM-1.0.1")                                \
  PARAM_DEF(UST_KGM_PER_M,                               0x000052D1, L"kg/m",                                        L"autodesk.unit.symbol:kgPerM-1.0.1")                                   \
  PARAM_DEF(UST_LB_MASS_PER_FT,                          0x00005335, L"lb/ft",                                       L"autodesk.unit.symbol:lbMassPerFt-1.0.1")                              \
  PARAM_DEF(UST_LBM_PER_FT,                              0x00005336, L"lbm/ft",                                      L"autodesk.unit.symbol:lbmPerFt-1.0.1")                                 \
  PARAM_DEF(UST_RAD,                                     0x00005399, L"rad",                                         L"autodesk.unit.symbol:rad-1.0.0")                                      \
  PARAM_DEF(UST_GRAD,                                    0x000053FD, L"grad",                                        L"autodesk.unit.symbol:grad-1.0.1")                                     \
  PARAM_DEF(UST_RAD_PER_S,                               0x00005461, L"rad/s",                                       L"autodesk.unit.symbol:radPerS-1.0.1")                                  \
  PARAM_DEF(UST_MS,                                      0x000054C5, L"ms",                                          L"autodesk.unit.symbol:ms-1.0.1")                                       \
  PARAM_DEF(UST_S,                                       0x00005529, L"s",                                           L"autodesk.unit.symbol:second-1.0.0")                                   \
  PARAM_DEF(UST_MIN,                                     0x0000558D, L"min",                                         L"autodesk.unit.symbol:min-1.0.1")                                      \
  PARAM_DEF(UST_H,                                       0x000055F1, L"h",                                           L"autodesk.unit.symbol:hour-1.0.1")                                     \
  PARAM_DEF(UST_KM_PER_H,                                0x00005655, L"km/h",                                        L"autodesk.unit.symbol:kmPerH-1.0.1")                                   \
  PARAM_DEF(UST_MI_PER_H,                                0x000056B9, L"mph",                                         L"autodesk.unit.symbol:mph-1.0.1")                                      \
  PARAM_DEF(UST_KJ,                                      0x0000571D, L"kJ",                                          L"autodesk.unit.symbol:kJ-1.0.1")                                       \
  PARAM_DEF(UST_KGM_PER_SQ_M,                            0x00005781, L"kg/m\u00B2",                                  L"autodesk.unit.symbol:kgPerMSup2-1.0.1")                               \
  PARAM_DEF(UST_LBM_PER_SQ_FT,                           0x000057E5, L"lb/ft\u00B2",                                 L"autodesk.unit.symbol:lbMassPerFtSup2-1.0.1")                          \
  PARAM_DEF(UST_WATTS_PER_METER_KELVIN,                  0x00005849, L"W/(m\u00B7K)",                                L"autodesk.unit.symbol:wPerMK-1.0.1")                                   \
  PARAM_DEF(UST_J_PER_G_CELSIUS,                         0x000058AD, L"J/(g\u00B7\u00B0C)",                          L"autodesk.unit.symbol:jPerGDegreeC-1.0.1")                             \
  PARAM_DEF(UST_J_PER_G,                                 0x00005911, L"J/g",                                         L"autodesk.unit.symbol:jPerG-1.0.1")                                    \
  PARAM_DEF(UST_NG_PER_PA_S_SQ_M,                        0x00005975, L"ng/(Pa\u00B7s\u00B7m\u00B2)",                 L"autodesk.unit.symbol:ngPerPaSMSup2-1.0.1")                            \
  PARAM_DEF(UST_OHM_M,                                   0x000059D9, L"ohm\u00B7m",                                  L"autodesk.unit.symbol:ohmM-1.0.1")                                     \
  PARAM_DEF(UST_BTU_PER_H_FT_DEGREE_F,                   0x00005A3D, L"BTU/(h\u00B7ft\u00B7\u00B0F)",                L"autodesk.unit.symbol:btuPerHFtDegreeF-1.0.1")                         \
  PARAM_DEF(UST_BTU_PER_LB_DEGREE_F,                     0x00005AA1, L"BTU/(lb\u00B7\u00B0F)",                       L"autodesk.unit.symbol:btuPerLbDegreeF-1.0.1")                          \
  PARAM_DEF(UST_BTU_PER_LB,                              0x00005B05, L"BTU/lb",                                      L"autodesk.unit.symbol:btuPerLb-1.0.1")                                 \
  PARAM_DEF(UST_GR_PER_H_SQ_FT_IN_HG,                    0x00005B69, L"gr/(h\u00B7ft\u00B2\u00B7inHg)",              L"autodesk.unit.symbol:grPerHFtSup2InHg-1.0.1")                         \
  PARAM_DEF(UST_PER_MILLE_SIGN,                          0x00005BCD, L"\u2030",                                      L"autodesk.unit.symbol:perMille-1.0.1")                                 \
  PARAM_DEF(UST_DM,                                      0x00005C31, L"dm",                                          L"autodesk.unit.symbol:dm-1.0.1")                                       \
  PARAM_DEF(UST_J_PER_KG_CELSIUS,                        0x00005C95, L"J/(kg\u00B7\u00B0C)",                         L"autodesk.unit.symbol:jPerKgDegreeC-1.0.1")                            \
  PARAM_DEF(UST_UM_PER_M_C,                              0x00005CF9, L"\u00B5m/(m\u00B7\u00B0C)",                    L"autodesk.unit.symbol:umPerMDegreeC-1.0.1")                            \
  PARAM_DEF(UST_UIN_PER_IN_F,                            0x00005D5D, L"\u00B5in/(in\u00B7\u00B0F)",                  L"autodesk.unit.symbol:uinPerInDegreeF-1.0.1")                          \
  PARAM_DEF(UST_USTONNES_MASS_TONS,                      0x00005DC1, L"Tons",                                        L"autodesk.unit.symbol:usTonnesMassTons-1.0.1")                         \
  PARAM_DEF(UST_USTONNES_MASS_T,                         0x00005DC2, L"T",                                           L"autodesk.unit.symbol:usTonnesMassT-1.0.1")                            \
  PARAM_DEF(UST_USTONNES_MASS_ST,                        0x00005DC3, L"ST",                                          L"autodesk.unit.symbol:usTonnesMassSt-1.0.1")                           \
  PARAM_DEF(UST_USTONNES_FORCE_TONSF,                    0x00005E25, L"Tonsf",                                       L"autodesk.unit.symbol:tonsf-1.0.1")                                    \
  PARAM_DEF(UST_USTONNES_FORCE_STF,                      0x00005E26, L"STf",                                         L"autodesk.unit.symbol:stf-1.0.1")                                      \
  PARAM_DEF(UST_USTONNES_FORCE_AS_MASS_TONS,             0x00005E27, L"Tons",                                        L"autodesk.unit.symbol:usTonnesForceTons-1.0.1")                        \
  PARAM_DEF(UST_USTONNES_FORCE_AS_MASS_T,                0x00005E28, L"T",                                           L"autodesk.unit.symbol:usTonnesForceT-1.0.1")                           \
  PARAM_DEF(UST_USTONNES_FORCE_AS_MASS_ST,               0x00005E29, L"ST",                                          L"autodesk.unit.symbol:usTonnesForceSt-1.0.1")                          \
  PARAM_DEF(UST_L_PER_M,                                 0x00005E89, L"L/min",                                       L"autodesk.unit.symbol:lPerMin-1.0.1")                                  \
  PARAM_DEF(UST_LPM,                                     0x00005E8A, L"LPM",                                         L"autodesk.unit.symbol:lpm-1.0.1")                                      \
  PARAM_DEF(UST_DEGREE_F_DIFFERENCE,                     0x00005EED, L"\u00B0F",                                     L"autodesk.unit.symbol:degreeFInterval-1.0.1")                          \
  PARAM_DEF(UST_DELTA_DEGREE_F,                          0x00005EEE, L"delta\u00B0F",                                L"autodesk.unit.symbol:deltaDegreeF-1.0.1")                             \
  PARAM_DEF(UST_DEGREE_C_DIFFERENCE,                     0x00005F51, L"\u00B0C",                                     L"autodesk.unit.symbol:degreeCInterval-1.0.1")                          \
  PARAM_DEF(UST_DELTA_DEGREE_C,                          0x00005F52, L"delta\u00B0C",                                L"autodesk.unit.symbol:deltaDegreeC-1.0.1")                             \
  PARAM_DEF(UST_KELVIN_DIFFERENCE,                       0x00005FB5, L"K",                                           L"autodesk.unit.symbol:kelvinInterval-1.0.0")                           \
  PARAM_DEF(UST_DELTA_KELVIN,                            0x00005FB6, L"deltaK",                                      L"autodesk.unit.symbol:deltaK-1.0.0")                                   \
  PARAM_DEF(UST_DEGREE_R_DIFFERENCE,                     0x00006019, L"\u00B0R",                                     L"autodesk.unit.symbol:degreeRInterval-1.0.1")                          \
  PARAM_DEF(UST_DELTA_DEGREE_R,                          0x0000601A, L"delta\u00B0R",                                L"autodesk.unit.symbol:deltaDegreeR-1.0.1")                             \
  PARAM_DEF(UST_US_SURVEY_FT,                            0x0000EC55, L"USft",                                        L"autodesk.unit.symbol:usft-1.0.0")                                     \

ODBM_ENUMERATION(UnitSymbolType, ODBM_UNITSYMBOLTYPE)

#endif // _BM_UNITSYMBOLTYPE_H_
